
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/csms?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: hao2003921120

    # Druid连接池配置
    druid:
      # 初始化连接数量
      initial-size: 5
      # 最小空闲连接数
      min-idle: 5
      # 最大活动连接数
      max-active: 20
      # 获取连接等待超时时间，单位毫秒
      max-wait: 60000
      # 配置检测连接是否有效的SQL语句，这里使用MySQL的示例
      validation-query: SELECT 1 FROM DUAL
      # 检测连接是否有效的间隔时间，单位秒
      time-interval: 60
      # 连接空闲多久后进行回收，单位秒
      idle-timeout: 300
      # 配置连接属性，例如设置自动提交等
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlTime=5000
      # 是否开启监控统计功能
      stat: true
      # 是否开启日志记录功能
      log: true