spring:
  datasource:
    url: jdbc:mysql://localhost:3306/course_design?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: hao2003921120
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      test-on-borrow: true
      test-on-return: true
      time-between-eviction-runs-milliseconds: 60000
      min-evictable-idle-time-milliseconds: 300000





mybatis - plus:
  configuration:
    log - impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
logging:
  level:
    com.example.dao: debug

server:
  port: 8080